### ISSUE TITLE
Feature request - Multiple 3commas accounts

### ISSUE THREAD

**Issue by enshoe** [AlexBabescu/freqtrade_3commas#1]
Hi,

Would it be possible to have the wrapper send the deal start to two different 3commas accounts? A second set of key, secret and bot ID's.

Its a bit of a fringe case, I am aware.

**Comment by AlexBabescu** [comment]
It's not a feature I plan on adding because it will overcomplicate things, but it's easy to implement by yourself.
Alternatively, you could just run two instances of freqtrade.

**Comment by thisisespria** [comment]
I followed the steps and added the following to my strategy and get errors when I run freqtrade.
    @Freqtrade3cw.buy_signal
    def populate_buy_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:

I get this error:
    raise OperationalException(
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'Strategy006'. This class does not exist or contains Python code errors.

It works without the buy_signal code. Any ideas?
